# Generated by Django 4.2.25 on 2025-10-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wubit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_am',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_am',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name_am',
        ),
    ]
