# Generated by Django 4.2.25 on 2025-10-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wubit', '0002_rename_description_am_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_snapshot',
        ),
    ]
