# Generated by Django 4.2.25 on 2025-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wubit', '0003_remove_cartitem_price_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='limage',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/'),
        ),
    ]
